### PR TITLE
Added extra param to control when to report based on suite values

### PR DESCRIPTION
**Pull request by l-urbini**
A simple param/function can now passed to decide if the report should be sent or not based on the decision logic passed around any suite value/property.

### CODE REVIEW

**Comment by l-urbini** [comment]
@estruyf have created this PR to introduce a new shouldRun param, be nice if we could get this merged/released as we wouldn't like to keep using our own forked version of the package.

**Comment by estruyf** [comment]
Thanks @siteriaitaliana would you be able to provide an example as well how and when you would use it?

**Comment by l-urbini** [comment]
> Thanks @siteriaitaliana would you be able to provide an example as well how and when you would use it?

Hi @estruyf sure..
in our case we only want to report when the project name contains a string e.g. '__jenkins' otherwise even our local runs report and the channel becomes pretty polluted, but i can honestly think this opens to much more flexibility and different user cases.

I have pushed a readme change with an example too.

**Review by estruyf — APPROVED** [review]
Looks good

**Comment by estruyf** [comment]
Thanks @siteriaitaliana for the update, I'll release the new version with this change.

**Pull request merged**
